### ISSUE TITLE
 Class 'yoast_i18n' not found. Version 1 instead of version 2.

### ISSUE THREAD

**Issue by RTC1** [Yoast/wpseo-news#314] opened 2017-08-15 12:29 UTC
After upgrading wpseo-news and wordpress-seo to version 5 the following error occurs when trying to access the SEO News admin area:

`Fatal error: Uncaught Error: Class 'yoast_i18n' not found in /home/vagrant/site/web/app/plugins/wpseo-news/classes/class-admin-page.php on line 80`

It appears that wpseo-news 5.2 requires version 1 of yoast_i18n, whilst wordpress-seo 5.2 requires version 2.

**Comment by CarolineGeven** [comment] 2017-12-05 08:59
I apologize for the late reply you are getting. Could you please tell me if this issue is still relevant? And if so, how to reproduce this? Unfortunately I'm unable to reproduce this and would like to know if this issue is perhaps already solved in the last months.

Thanks for your patience and again, I apologize that no one got back to you sooner.

**Comment by moorscode** [comment] 2018-06-08 10:17
We are currently at version 3.0, so this issue has been resolved in the past.

**Closed by moorscode** 2018-06-08 10:17 UTC
