### ISSUE TITLE
Link Rel Original Source

### ISSUE THREAD

**Issue by Mossy17** [Yoast/wpseo-news#18] opened 2012-12-23 14:36 UTC
Hi,

Not sure if this is intentional or not (Google guidelines are a bit sketchy), after upgrading to the latest version (I use the wordpress plugin) the rel original source no longer defaults to the the published blog post?

Pretty sure it used to default to the publised post. Now it's just a blank href=" "

Google news blog says "In both cases, it's perfectly valid for a metatag to point to the current page URL"

I could just self reference manually. But wondered if there is a way to default to the current post URL, if that is a best practice.

Thanks,

J

**Comment by CarolineGeven** [comment] 2016-12-08 12:08
Closing this as this issue cannot be reproduced/seems to be fixed in the current version.

If the issue persists, please create a new bug report with the relevant information and steps to reproduce.

**Closed by CarolineGeven** 2016-12-08 12:08 UTC
